# Generated by Django 4.0 on 2022-01-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_esp', models.CharField(max_length=30, unique=True, verbose_name='Nombre Especialidad')),
                ('descrip', models.TextField(verbose_name='Descripción de Especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=3, unique=True, verbose_name='Identificación')),
                ('nomb', models.CharField(max_length=50, verbose_name='Nombre del Paciente')),
                ('ape', models.CharField(max_length=50, verbose_name='Apellido del Paciente')),
                ('num_te', models.CharField(max_length=30, verbose_name='Numero de Telefono')),
                ('dirc', models.CharField(max_length=100, verbose_name='Dirección')),
                ('ciud_resid', models.CharField(max_length=100, verbose_name='Ciudad de Residencia')),
                ('fecha_naci', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=3, unique=True, verbose_name='Identificación')),
                ('nomb', models.CharField(max_length=50, verbose_name='Nombre del Médico')),
                ('ape', models.CharField(max_length=50, verbose_name='Apellido del Médico')),
                ('num_te', models.CharField(max_length=30, verbose_name='Numero de Telefono')),
                ('dirc', models.CharField(max_length=100, verbose_name='Dirección')),
                ('ciud_resid', models.CharField(max_length=100, verbose_name='Ciudad de Residencia')),
                ('fecha_naci', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('especialidad', models.ManyToManyField(to='hospA.Especialidad')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
    ]
